:concurrency: 4
:queues:
  - ['default', 2]
  - ['send_present', 3]
  - ['mailer', 4]
  - ['send_future', 3]
  - ['error_retry', 5]

tasks: &tasks
  schedule_job:
    class: FutureMailJob
    every: ["10s", first_in: "5s"]
    queue: "send_future"

  present_mail_job:
    cron: "*/15 * * * *"
    class: SendMailWorker
:schedule:
  <<: *tasks